mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.ssl.trust=smtp.gmail.com

mail.username=tonadresse@gmail.com
mail.password=motdepasse_ou_mot_de_passe_application