
# =========================================
# PAYDUNYA LIVE
# =========================================

paydunya.master.key=STucrGvO-zqXe-T5Sj-1Fh1-NG4En3xEgMgt

paydunya.public.key=live_public_XLHdjAiizRY1Q57W738o3WgY31S

paydunya.private.key=live_private_hRH1YXfa4ZC30Qg0J13J2Ggwjy0

paydunya.token=taBhwdwnabiA6mGukjko

# =========================================
# URLS NGROK
# =========================================

paydunya.callback.url=https://sanctity-unsent-giddiness.ngrok-free.dev/amical-ard/etudiant/paydunya/callback

paydunya.success.url=https://sanctity-unsent-giddiness.ngrok-free.dev/amical-ard/etudiant/caravanes?success=true

paydunya.cancel.url=https://sanctity-unsent-giddiness.ngrok-free.dev/amical-ard/etudiant/caravanes?cancel=true

